implemented car, user and rental repositories and services
PlagueEbola/Car-Sharing-Service-Project pull request #5
Opened 2023-05-29 17:36 UTC by Deschna

2023-05-29 18:14 UTC, PlagueEbola submitted a review, later dismissed

2023-05-30 07:34 UTC, PlagueEbola approved these changes, later dismissed

2023-05-30 08:08 UTC, De1eF requested changes

2023-05-30 08:08 UTC, De1eF commented on src/main/java/com/example/car_sharing_sertvice_project/model/User.java
> -    @EqualsAndHashCode.Exclude
Put EqualsAndHashCode.Exclude back together with EqualsAndHashCode as class annotation in all models

2023-05-30 08:23 UTC, De1eF approved these changes

2023-05-30 08:23 UTC, PlagueEbola approved these changes

2023-05-30 08:24 UTC, merged